-- Migration: Make `id` columns GENERATED AS IDENTITY for categories and medicines
-- Run this in Supabase SQL editor or psql connected to the database.
-- It is defensive: it only applies the ALTER if the column is not already an identity.
-- It preserves existing data and primary key constraints.

-- Categories
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'categories' AND column_name = 'id' AND is_identity = 'YES'
  ) THEN
    BEGIN
      -- Try dropping an existing default (e.g. nextval(seq)) if present; ignore errors
      BEGIN
        ALTER TABLE public.categories ALTER COLUMN id DROP DEFAULT;
      EXCEPTION WHEN others THEN
        -- ignore
        NULL;
      END;
      -- Convert to identity (GENERATED BY DEFAULT so existing values are preserved)
      ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END;
  END IF;
END$$;

-- Medicines
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'medicines' AND column_name = 'id' AND is_identity = 'YES'
  ) THEN
    BEGIN
      BEGIN
        ALTER TABLE public.medicines ALTER COLUMN id DROP DEFAULT;
      EXCEPTION WHEN others THEN
        NULL;
      END;
      ALTER TABLE public.medicines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END;
  END IF;
END$$;

-- Notes / Post-checks:
-- 1) After running, test inserting rows without `id` to ensure sequence increments:
--    INSERT INTO categories (nama_kategori) VALUES ('tes');
--    INSERT INTO medicines (nama_obat, kategori, gejala, deskripsi, harga, foto_url) VALUES ('tes', 1, 'demam', 'desc', 1000, '');
-- 2) If you see conflicts because sequences start below existing max(id), run:
--    SELECT setval(pg_get_serial_sequence('categories','id'), COALESCE(MAX(id),1)) FROM categories;
--    SELECT setval(pg_get_serial_sequence('medicines','id'), COALESCE(MAX(id),1)) FROM medicines;
-- 3) Backup your DB before running migrations.
